### PR TITLE
Upgrade Node v18

### LINKED ISSUE #197: [Enhancement] Bump node from v8 to v18 LTS (and therefore bump packages too)
https://github.com/NREL/OpenStudio-PAT/blob/ee3c6c44156d9409d876f12115e681022cafb21b/package.json#L71-L73

Node v16 is the current LTS version.

Node.js 8 was initially released on 2017-05-30, and its End-of-Life was 31st December 2019, so it's been EOL since more than 2 years.

**Sub Task Issues**
- [x] #211
- [x] #212
- [x] #213
- [x] #214
- [x] #215
- [x] #216
- [x] #217
- [x] #221

### LINKED ISSUE #211: Upgrade gulp to v4
**~3.9.1 → ~4.0.2**
Required for Node v18 (#197)

gulp v3 does not support Node v12+ (see https://github.com/gulpjs/gulp/issues/2324). The following error is given when attempting to run gulp v3 with Node v18: `ReferenceError: primordials is not defined`

### LINKED ISSUE #212: Upgrade gulp-sass to v5 & replace node-sass with sass
**~3.1.0 → ~5.1.0**
Required for Node v18 (#197)

gulp-sass v3 uses [node-sass](https://www.npmjs.com/package/node-sass) as the default Sass compiler, which [is deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and does not support Node v18. The authors recommend using dart [sass](https://www.npmjs.com/package/sass) as a replacement.

gulp-sass v5 supports Node v12+ and allows setting the Sass compiler, per the [migration guide](https://www.npmjs.com/package/gulp-sass#migrating-to-version-5).

### LINKED ISSUE #213: Upgrade vinyl-source-stream to v2
**^1.1.0 → ~2.0.0**
Required for Node v18 (https://github.com/NREL/OpenStudio-PAT/issues/197)

The following error is given when attempting to run the install-deps gulp task with vinyl-source-stream v1 and Node v18: `` Error: Received a non-Vinyl object in `dest()` ``

### LINKED ISSUE #214: Upgrade browser-sync to v2.27.10
**~2.13.0 → ~2.27.10**
Required for Node v18 (#197)

The following warning is printed when when attempting to use browser-sync v2.13.0 with Node v18:
<code>(node:89870) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;at SendStream.isFresh (/Users/baileystein/OpenStudio-PAT/node_modules/send/index.js:372:43)</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;at SendStream.send (/Users/baileystein/OpenStudio-PAT/node_modules/send/index.js:539:13)</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;at onstat (/Users/baileystein/OpenStudio-PAT/node_modules/send/index.js:624:10)</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;at FSReqCallback.oncomplete (node:fs:212:5)</code>

Upon further investigation, the `send@0.13.2` package is a dependency of `serve-static@1.10.3`, which is a dependency of `browser-sync@2.13.0`.

browser-sync v2.27.10 uses `serve-static@1.13.2` per its [package.json](https://github.com/BrowserSync/browser-sync/blob/f6965a67277bdadfaa4943e7b90e4ed6a71e90af/packages/browser-sync/package.json#L63), which uses `send@0.16.2` per its [package.json](https://github.com/expressjs/serve-static/blob/f287bd6c26ad2bfd0422c533b0358f2f4b16f7db/package.json#L12). `send@0.16.2` should not produce this deprecation warning.

### LINKED ISSUE #215: Upgrade asar to v3
**~0.10.0 → ~3.2.0**
Required for Node v18 (https://github.com/NREL/OpenStudio-PAT/issues/197)

asar@0.10.0 has downstream dependencies of graceful-fs@3.0.11, which does not support Node v18. The following warning is printed when running `npm i`: `npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js`

After upgrading asar, code changes will need to be made to `./tasks/release_linux.js`, `./tasks/release_macos.js`, and `./tasks/release_windows.js`. In asar@0.10.0, the createPackage() function accepted a callback as a third argument. In asar@3.2.0, however, the function is asynchronous and does not accept a callback (see [example](https://github.com/electron/asar#example)).

### LINKED ISSUE #216: Upgrade main-bower-files to v2.13.3
**~2.11.1 → ~2.13.3**
Required for Node v18 (https://github.com/NREL/OpenStudio-PAT/issues/197)

main-bower-files@2.13.3 depends on vinyl-fs@1.0.0, which depends on graceful-fs@3.0.12 and has a downstream dependency of graceful-fs@1.2.3. As explained in #215, versions of graceful-fs prior to v4 do not support Node v18.

### LINKED ISSUE #217: Remove karma packages
Required for Node v18 (https://github.com/NREL/OpenStudio-PAT/issues/197)

karma@0.13.22 does not support Node v18. The following warning is printed to the console:
<code>npm WARN EBADENGINE Unsupported engine {</code>
<code>npm WARN EBADENGINE &nbsp;&nbsp;package: 'karma@0.13.22',</code>
<code>npm WARN EBADENGINE &nbsp;&nbsp;required: { node: '0.10 || 0.12 || 4 || 5' },</code>
<code>npm WARN EBADENGINE &nbsp;&nbsp;current: { node: 'v18.7.0', npm: '8.15.0' }</code>
<code>npm WARN EBADENGINE }</code>

There are newer versions of karma available that work with Node v18, but since karma is not being used in this project, it should be removed along with its related packages:
- `karma`
- `karma-coverage`
- `karma-jasmine`
- `karma-ng-html2js-preprocessor`
- `karma-phantomjs-launcher`
- `phantomjs-prebuilt`

### LINKED ISSUE #220: Update README with build instructions
Somewhat similar to [the documentation](https://github.com/NREL/EnergyPlus/wiki/Building-EnergyPlus) for building EnergyPlus

### LINKED ISSUE #221: Replace gulp-decompress with tar-fs
Previously, we were using `gulp-decompress@2.0.1` and [while upgrading](https://github.com/NREL/OpenStudio-PAT/pull/218#issuecomment-1206793175) to Node v18 (#197), I discovered there was a bug where symbolic links / "aliases" are incorrectly decompressed as empty executable files.

Although `gulp-decompress@2.0.3` fixed this particular issue, the upgrade caused a new issue when running on Windows where symbolic links couldn't be resolved. I believe this issue is related, although the "fix" does not work for our use case: https://github.com/gulpjs/vinyl-fs/issues/210

As a resolution, we can instead use the built-in `zlib` node module for gunzipping and the [`tar-fs`](https://www.npmjs.com/package/tar-fs) package for extracting the .tar file.

### PR DESCRIPTION
**Pull request by bstein**
Using Node v18.7.0, I tested the gulp installDeps, build, and release tasks following the upgrade on macOS 12.4, Windows 10, and Ubuntu 22.04 (Linux). I also tested the cmake build process on macOS 12.4. Everything is working as expected.

### CODE REVIEW

**Comment by tijcolem** [comment]
@bstein  This is a great start to get the update moving along to node18 and electron.  I was able to build this on my mac (10.15.7) using node v18.7.0 but I hit an error when running the [Office_HVAC](https://github.com/NREL/OpenStudio-PAT/tree/develop/sample_projects/Office_HVAC) sample project.   I captured the console logs and screen grabs to compare the latest node18 build vs the 3.4.0 node8 build.  Can you run this example project on one of your builds to see if you hit the same error? 

*This branch (upgrade-node-v18) with node18.7.0.*
Screen Shot 2022-08-03 at 4 23 14 PM

[node_18_console.log](https://github.com/NREL/OpenStudio-PAT/files/9255390/node_18_console.log)

*Previous 3.4.0 release*
Screen Shot 2022-08-03 at 3 36 27 PM
[node_8_console.log](https://github.com/NREL/OpenStudio-PAT/files/9255391/node_8_console.log)

**Comment by bstein** [comment]
@tijcolem I was able to reproduce this same issue on my machine. Interestingly, it seems to work fine when I run it with `npm start`, but I encounter this issue when opening the .app file from ./tmp or from where the built installer installs it to. I will investigate further.

**Comment by bstein** [comment]
@tijcolem I looked into the issue and have some updates:

**Observations**
Strangely, I am also seeing this issue when building the project as-is on the develop branch with Node 8 on my machine running macOS 12.4 Monterey. The only time I don't see this issue is when I install PAT using the [pre-built 3.4.0 installer](https://github.com/NREL/OpenStudio-PAT/releases/tag/v3.4.0), which I refer to as "stable" below.

**Problem**
It seems that when `EnergyPlus-22.1.0-darwin.tar.gz` is decompressed, the aliases for things like `energyplus` are incorrectly extracted as Unix executable files. This is problematic as the OpenStudio server tries to execute the "empty" executable; instead, it should've been an alias to the actual executable.

Stable (in Resources)         |  Actual / System decompressed | Built on 12.4 (in Resources)
:-------------------------:|:-------------------------:|:-------------------------:
in-resources-stable | system-decompressed | in-resources-node18

Also remarkable is the fact that the aliases are missing entirely for the stable app.

**Questions**
1.  When you performed your testing, did you use the pre-built installer ("stable") as well? Or did you perform a build while on the develop branch and then use the installer?
2. What version of macOS did you use to build the stable installer? What version of macOS are you using now?
3. Which version of Node 8 and npm did you use? You can check with `node -v` and `npm -v`

I will continue looking into this and attempt to find a solution.

**Comment by bstein** [comment]
It looks like this was a bug in `gulp-decompress` that they resolved in `v2.0.3`: https://github.com/kevva/gulp-decompress/pull/21

Therefore, upgrading `gulp-decompress` should resolve this issue. I am going to do that and then run some tests to be sure.

**Comment by bstein** [comment]
I updated this PR to use `gulp-decompress@~3.0.0`. I tested it locally by building the installer, installing PAT, and then running the Office_HVAC project.

**Comment by tijcolem** [comment]
@bstein I added a github action to build PAT on Ubuntu-18.04, Windows 2019 & macOS 10.15.  Ubuntu and Mac are building fine which is a what I expected as I could build locally on my mac 10.15. However, Windows is causing a problem. I've also tested this on a local Windows machine and I am getting the same error as reported on the CI - https://github.com/NREL/OpenStudio-PAT/runs/7752932020?check_suite_focus=true#step:6:207 

It looks like a step right after it downloads the dependencies defined in the manifest and something with symlinks but it's not really clear what the exact problem is.  I also tested this on the same CI machine we used to build PAT with node v8 and I got the same error, so it appears related to the node v18 update.  Could you please take a look?

**Comment by bstein** [comment]
@tijcolem Of course! I will look into this and post an update once I find a solution.

**Comment by bstein** [comment]
I updated this PR to fix the issue on Windows when running the `installDeps` task. I documented this issue here: https://github.com/NREL/OpenStudio-PAT/issues/221

**Comment by tijcolem** [comment]
@bstein That's great you resolved that!  Sadly I found another issue on Windows. :( 

I tested the windows installer that was saved as an artifact on GH actions and many of the exes were missing on Windows. Looking at this further it appears to be related to using msvc 2019 vs the previous 2013. I confirmed that 2013 still builds fine so it's for sure related to the new version. I added a couple of config lines on my last commit so we'll see if that fixes it.  I don't know node-gyp well enough to know if 2019 is supported and I couldn't find documentation around this on https://github.com/nodejs/node-gyp.   If my last commit doesn't work I can try msvc 2022 as well. That probably makes more sense anyway.  

This is the error causing the problem. https://github.com/NREL/OpenStudio-PAT/runs/7772495872?check_suite_focus=true#step:6:219  Not sure why this didn't result in a non-zero exit.

**Comment by bstein** [comment]
@tijcolem Thank you for documenting this. I just configured a separate machine running Windows so I can test this further, since the virtual machine I was using was very slow. I discovered there are some issues during the build task on Windows where files aren't being flattened properly. I am not sure why this issue isn't showing up on MacOS or Linux, but I will keep investigating and work on fixes.

**Comment by tijcolem** [comment]
@bstein Thanks for looking into it.  I also tried to use Visual Studio 2022 but the last build received the same problem.

**Comment by bstein** [comment]
@tijcolem Quick update: While I managed to fix the other issues I found this morning, I am still looking into this build issue

**Comment by bstein** [comment]
@tijcolem I made a couple more changes to the gulp tasks so the files are flattened as expected on Windows. I also updated some of the build files and summarized the changes below. Finally, I downloaded the .exe installer artifact from the GitHub build and was able to install and run PAT on my Windows machine. **I believe everything is working as expected now.**

**build_pat.yaml**
- Ensure node version is set using node-version (previously we were setting python-version, which has no effect)
- Updated reference to "Visual Studio 17 2022" (previously we were saying "Visual Studio 16 2019")
- Use Ubuntu 22.04 instead of 18.04, since Node 18 does not work on 18.04

**BuildPat.txt**
- `cd` out of build directory before trying to run npm commands & `bower install` command (previously, these would not install dependencies)
- Remove unnecessary `npm install bower` command, since `bower` is already listed as a dev dependency in `package.json`

**Comment by tijcolem** [comment]
@bstein This is great! Nice work getting the problems ironed out on windows. I'm super happy we can move to using MSVC 2022 to build. Also, thanks for bumping to latest ubuntu version as well.  I'll grab on the Windows installers and give it a test as well.

**Comment by bstein** [comment]
@tijcolem Did you have a chance to test it out on Windows? Please let me know once we can get this merged in – thanks!

**Comment by tijcolem** [comment]
@bstein I'll test this morning.  Great that this is ready to merge pending outcome of my sanity test.

**Comment by tijcolem** [comment]
@bstein Tested windows installer on a clean 2019 Windows instance and everything ran great!  This is good to drop in.

**Review by tijcolem — APPROVED** [review]

**Pull request merged**
