### PR TITLE
Upgrade electron to v20

### LINKED ISSUE #219: Upgrade electron to latest version (v20)
**^1.7.11 → ~20.0.3**

This issue tracks the work of upgrading to the latest version of electron. The project should be updated one major version at a time (eg, v1 to v2 to v3 etc). For each major version update, any [breaking changes](https://www.electronjs.org/docs/latest/breaking-changes) should be fixed and the application should be tested.

### Relevant Breaking Changes by Version

- [x] **v2 - [release notes](https://github.com/electron/electron/releases/tag/v2.0.0)**
None
- [x] **v3 - [release notes](https://github.com/electron/electron/releases/tag/v3.0.0)**
None
- [x] **v4 - [release notes](https://github.com/electron/electron/releases/tag/v4.0.0)**
None
- [x] **v4 - [release notes](https://github.com/electron/electron/releases/tag/v4.0.0)**
- `Electron Helper EH` and `Electron Helper NP` apps are no longer generated and only `Electron Helper` remains
    - [x] Rename only `Electron Helper` app during the gulp release task for MacOS
- [x] **v5 - [release notes](https://github.com/electron/electron/releases/tag/v5.0.0)**
- `nodeIntegration` and `webviewTag` were changed to be false by default: https://github.com/electron/electron/pull/16235
    - [x] Set `nodeIntegration` and `webviewTag` to true
- [x] **v6 - [release notes](https://github.com/electron/electron/releases/tag/v6.0.0)**
- `dialog.showMessageBox()` was split into two functions and the original became asynchronous: https://github.com/electron/electron/pull/17298
    - [x] Use new asynchronous `showMessageBox()` function
- `dialog.showOpenDialog()` was split into two functions and the original became asynchronous: https://github.com/electron/electron/pull/16973
    - [x] Use new asynchronous `showOpenDialog()` function
- `Electron Helper (GPU)`,  `Electron Helper (Plugin)`, and `Electron Helper (Renderer)` apps are now generated in addition to `Electron Helper`
    - [x] Rename all `Electron Helper` apps during the gulp release task for MacOS
- [x] **v7 - [release notes](https://github.com/electron/electron/releases/tag/v7.0.0)**
- `electron.asar` file was removed: https://github.com/electron/electron/pull/18577
    - This exposed a bug in `reportsController` when in dev environment. When importing `env`, `__dirname` is `/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer`, which does not contain the `env.json` file; when `env` is used in `background.js`, the __dirname is `./build`, which does contain the `env.json` file
    - [x] Correctly access the `env.json` file by using the appPath instead of __dirname
- `shell.openExternal()` was split into two functions and the original became asynchronous:  https://github.com/electron/electron/pull/16176
     - [x] Use new asynchronous `openExternal()` function
- `webviewTag.executeJavaScript()` was split into two functions and the original became asynchronous:  https://github.com/electron/electron/pull/17312
     - [x] Use new asynchronous `executeJavaScript()` function
- Although it seems it was not documented, `app.getName()` was deprecated in favor of the `app.name` property
     - [x] Use `app.name` instead of `app.getName()`
- [x] **v8 - [release notes](https://github.com/electron/electron/releases/tag/v8.0.0)**
None
- [x] **v9 - [release notes](https://github.com/electron/electron/releases/tag/v9.0.0)**
- `shell.openItem()` was converted into an asynchronous function named `shell. openPath()`:  https://github.com/electron/electron/pull/20682
     - [x] Use new asynchronous `openPath()` function
- [x] **v10 - [release notes](https://github.com/electron/electron/releases/tag/v10.0.0)**
- `enableRemoteModule` was changed to be false by default: https://github.com/electron/electron/pull/22091
    - [x] Set `enableRemoteModule` to true
- [x] **v11 - [release notes](https://github.com/electron/electron/releases/tag/v11.0.0)**
None
- [x] **v12 - [release notes](https://github.com/electron/electron/releases/tag/v12.0.0)**
- The `remote` module was deprecated and replaced by `@electron/remote`: https://github.com/electron/electron/pull/25293
    - [x] Migrate from `remote` module to `@electron/remote` package
- The default value of `contextIsolation` was changed to be true: https://github.com/electron/electron/pull/27949
    - [x] Explicitly set `contextIsolation` to false
- The default value of `worldSafeExecuteJavaScript` was changed to be true: https://github.com/electron/electron/pull/27502
    - [x] Explicitly set `worldSafeExecuteJavaScript` to false
- [x] **v13 - [release notes](https://github.com/electron/electron/releases/tag/v13.0.0)**
None
- [x] **v14 - [release notes](https://github.com/electron/electron/releases/tag/v14.0.0)**
- Dropped support for `@electron/remote@1.x`
    - [x] Migrate to `@electron/remote@2.x`: https://github.com/electron/remote/blob/main/docs/migration-2.md 
- [X] **v15 - [release notes](https://github.com/electron/electron/releases/tag/v15.0.0)**
None
- [x] **v16 - [release notes](https://github.com/electron/electron/releases/tag/v16.0.0)**
- The `webview` was improved and renders differently
    -  [x] To avoid rendering issues, yse the `ng-src` directive instead of `src` on the [`server.html` file](https://github.com/NREL/OpenStudio-PAT/blob/34a0c67fa4cd739697761a2f24dfbb5ca38b3c0b/app/app/server/server.html#L17) (also [see explanation](https://stackoverflow.com/a/27554935))
- [x] **v17 - [release notes](https://github.com/electron/electron/releases/tag/v17.0.0)**
None
- [x] **v18 - [release notes](https://github.com/electron/electron/releases/tag/v18.0.0)**
None
- [x] **v19 - [release notes](https://github.com/electron/electron/releases/tag/v19.0.0)**
None
- [x] **v20 - [release notes](https://github.com/electron/electron/releases/tag/v20.0.0)**
None

### PR DESCRIPTION
**Pull request by bstein**
This pull request bumps the version of electron from v1.7.11 to v20.0.3 and includes fixes for breaking changes that were introduced in various major versions of electron. A detailed account of changes by version is available in #219.

Additionally, because electron v11 and later support running natively on Apple Silicon, I updated the build command for MacOS to target MacOS 11 Big Sur as well as both x86 and ARM. The updated command builds a Universal App which can be installed on both Intel and Apple Silicon Macs without requiring emulation.

### CODE REVIEW

**Comment by tijcolem** [comment]
@bstein This looks great. I tested the installers out and ran a simple analysis and all looked good on my end.

**Comment by tijcolem** [comment]
@bstein I am tagging @kflemin to do a code review on the proposed changes. From my end the PAT app itself seems to be working great.

**Review by kflemin — COMMENTED** [review]
^1.7.11 → ~20.0.1🤯
Wow @bstein, thank you for making this upgrade!  

Everything looks good to me except the server tab is not loading the server view (it says cannot GET url...) 
Screen Shot 2022-08-25 at 10 28 22 AM

I haven't used PAT in a while so i'm not sure when this page stopped working, but perhaps during this update? @tijcolem, have you noticed this before?

**Comment by tijcolem** [comment]
@kflemin Those are NREL internal URLs http://bball-13055.nrel.gov:8080.  Maybe this was something saved in one of your PAT build projects?  If this is something in PAT itself we'd want to get this removed

**Comment by kflemin** [comment]
@tijcolem, this page should show whatever server PAT connected to (remote , local, whatever). I just happened to connect to that one. I haven't tested with other ones or local or anything. Can you get that page to show any server?

**Comment by tijcolem** [comment]
@kflemin Okay, I see what you are saying. I tested out the 3.4.0 release and it shows the page with server dashboard as it appears on http://localhost:8080. But when I test with the updated electron app v20I get the blank screen. 

3.4.0 server screen (electron v1)
Screen Shot 2022-08-25 at 2 45 24 PM

3.4.0 server screen (electron v20)
Screen Shot 2022-08-25 at 2 51 27 PM

@bstein Could you investigate?

**Comment by bstein** [comment]
@tijcolem @kflemin

It appears there were some changes in Electron v16 related to the `<webview>` tag, which holds the server page. This surfaced some buggy behavior when using the `src` attribute in the [`server.html` file](https://github.com/NREL/OpenStudio-PAT/blob/34a0c67fa4cd739697761a2f24dfbb5ca38b3c0b/app/app/server/server.html#L17). By using the `ng-src` directive, we avoid these issues ([see explanation](https://stackoverflow.com/a/27554935)).

This PR should now be ready for re-review 👍

**Review by kflemin — APPROVED** [review]
Looks great now! thanks for the fix!

**Comment by tijcolem** [comment]
Fantastic! Going to merge.

**Pull request merged**
