### PR TITLE
deprecation warning

### PR DESCRIPTION
**Pull request by kflemin**
deprecation warning shown once per session on run tab, when selecting run on remote server.
Screen Shot 2020-03-05 at 8 48 41 PM

### CODE REVIEW

**Comment by anyaelena** [comment]
Thanks @kflemin! Wording update:

Deprecation Warning: version 3.1 of PAT will not include the Amazon Cloud Remote Server option. Please review the OpenStudio Server 3.0.0 [release notes]( https://github.com/NREL/OpenStudio-server/releases) for additional details related to cloud deployment.

**Comment by anyaelena** [comment]
@kflemin @brianlball just a bump to make sure this isn't overlooked for 3.0.0

**Comment by brianlball** [comment]
good to me

**Comment by kflemin** [comment]
I updated the wording. I couldn't get the link in the message though, but I think it's good to go.

**Pull request merged**
